function choice = dialogRR()



    choice.initials = 'jonmarc';
    choice.booth    = 'PHY2';
    choice.phone    = 'ER3';
    choice.level    = 94.8;
    choice.refFreq  = 1000;
    choice.devID    = find_ASIO_devID;
    choice.InChan   = 5;
    
    d               = dialog('Position',[200 300 250 450],'Name','Start Calibration');
    
    title_txt       = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 420 210 20],...
           'String','** HEA CALIBRATION **','fontsize',12);
       
    date_txt        = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 400 210 20],...
           'String',date);
       
    initials_txt    = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 350 210 40],...
           'String','Set Initials');
       
    initals_edit    = uicontrol('Parent',d,...
           'Style','edit',...
           'Position',[75 345 100 25],...
           'String',choice.initials,...
           'Callback',@initials_edit_callback);
       
    booth_txt       = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 295 210 40],...
           'String','Select Booth');
       
    booth_popup     = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 290 100 25],...
           'String',{'PSY1';'PSY2';'PSY3';'PSY4';'PHY1';'PHY2';'COM1';'COM2';'BBH1';'BBH6';'CLINIC'},...
           'Callback',@booth_popup_callback);
       
    phon_txt        = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 240 210 40],...
           'String','Select Headphone');
       
    phon_popup      = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 235 100 25],...
           'String',{'HD650';'HDA200';'ER2';'ER3'},...
           'Callback',@phon_popup_callback);
       
    fs_txt        = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 190 210 40],...
           'String','Select samplerate');
       
    fs_popup      = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 185 100 25],...
           'String',{'48000';'44100'},...
           'Callback',@fs_popup_callback);       
    
    reference_text  = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 140 210 40],...
           'String','Set Reference');
       
    reference_popup	= uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[75 135 100 25],...
           'String',{'94.8 dB SPL @ 1 kHz';'114 dB SPL @ 250 Hz';'Custom'},...
           'Callback',@reference_callback);   
     
     
    devID_txt       = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 50 210 20],...
           'String',['ASIO device ID: ' num2str(choice.devID) ]);
       
    channel_txt     = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 70 210 20],...
           'String',['Input Channel: ' num2str(choice.InChan)]);   
    
    find_chan       = uicontrol('Parent',d,...
           'Position',[89 100 70 15],...
           'String','Identify Input',...
           'TooltipString','Identify and change current signal input channel for calibration',...
           'Callback',@find_chan_callback);   
       
    start_run       = uicontrol('Parent',d,...
           'Position',[89 10 70 25],...
           'String','Start',...
           'Callback',@start_run_callback);

    
    % Wait for d to close before running to completion
    uiwait(d);
   
        function initials_edit_callback(initials_edit,callbackdata)
          level_edit_items = initials_edit.String;
          choice.initials = char(level_edit_items);
        end
    
        function booth_popup_callback(booth_popup,callbackdata)
          idx = booth_popup.Value;
          booth_popup_items = booth_popup.String;
          choice.booth = char(booth_popup_items(idx,:));
        end
    
        function phon_popup_callback(phon_popup,callbackdata)
          idx = phon_popup.Value;
          phon_popup_items = phon_popup.String;
          choice.phone = char(phon_popup_items(idx,:));
        end
    
        function fs_popup_callback(fs_popup,callbackdata)
          idx = fs_popup.Value;
          fs_popup_items = fs_popup.String;
          choice.fs = str2double(fs_popup_items(idx,:));
        end    
    
        function reference_callback(reference_popup,callbackdata)
            idx = reference_popup.Value;

            if idx    == 1,
                choice.level   	= 94.8;
                choice.refFreq 	= 1000;
            elseif idx ==2,
                choice.level   	= 114;
                choice.refFreq 	= 250;
            else
                prompt = {'Enter  Level [dB SPL]:','Enter Frequency [Hz]:'};
                dlg_title = 'Reference Properties';
                num_lines = 1;
                def = {'94.8','1000'};
                answer = inputdlg(prompt,dlg_title,num_lines,def);
                choice.level   	= str2double(strrep(answer{1},',','.'));
                choice.refFreq	= str2double(strrep(answer{2},',','.'));
            end
             
        end
        
        function find_chan_callback(channel_txt,callbackdata)
          choice.InChan = find_INPUT_channel;
          choice.calib  = 1;
        end
    
        function start_run_callback(start_run,callbackdata)
            choice.calib = 1; 
            delete(gcf)
        end
     	
    
          
    
end
